# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mcproto.mcproto.protos.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x08launcher\x1a\x0c\x63ommon.proto\"\x13\n\x11GetProfileRequest\">\n\x12GetProfileResponse\x12(\n\x07profile\x18\x01 \x01(\x0b\x32\x17.launcher.PlayerProfile\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"t\n\rLoginResponse\x12)\n\x0csession_data\x18\x03 \x01(\x0b\x32\x11.launcher.SessionH\x00\x12.\n\x0cmfa_required\x18\x04 \x01(\x0b\x32\x16.launcher.MfaChallengeH\x00\x42\x08\n\x06result\"?\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x07profile\x18\x02 \x01(\x0b\x32\x17.launcher.PlayerProfile\"\x0e\n\x0cMfaChallenge\"\x0f\n\rLogoutRequest\"\x10\n\x0eLogoutResponse2\xcd\x01\n\x0b\x41uthService\x12\x38\n\x05Login\x12\x16.launcher.LoginRequest\x1a\x17.launcher.LoginResponse\x12;\n\x06Logout\x12\x17.launcher.LogoutRequest\x1a\x18.launcher.LogoutResponse\x12G\n\nGetProfile\x12\x1b.launcher.GetProfileRequest\x1a\x1c.launcher.GetProfileResponseB\x1f\n\x1bnet.mcsgroup.launcher.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033net.mcsgroup.launcher.protoP\001'
  _globals['_GETPROFILEREQUEST']._serialized_start=38
  _globals['_GETPROFILEREQUEST']._serialized_end=57
  _globals['_GETPROFILERESPONSE']._serialized_start=59
  _globals['_GETPROFILERESPONSE']._serialized_end=121
  _globals['_LOGINREQUEST']._serialized_start=123
  _globals['_LOGINREQUEST']._serialized_end=173
  _globals['_LOGINRESPONSE']._serialized_start=175
  _globals['_LOGINRESPONSE']._serialized_end=291
  _globals['_SESSION']._serialized_start=293
  _globals['_SESSION']._serialized_end=356
  _globals['_MFACHALLENGE']._serialized_start=358
  _globals['_MFACHALLENGE']._serialized_end=372
  _globals['_LOGOUTREQUEST']._serialized_start=374
  _globals['_LOGOUTREQUEST']._serialized_end=389
  _globals['_LOGOUTRESPONSE']._serialized_start=391
  _globals['_LOGOUTRESPONSE']._serialized_end=407
  _globals['_AUTHSERVICE']._serialized_start=410
  _globals['_AUTHSERVICE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
