# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x08launcher\"A\n\rPlayerProfile\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08skin_url\x18\x03 \x01(\t*g\n\rIntegrityMode\x12\x1e\n\x1aINTEGRITY_MODE_UNSPECIFIED\x10\x00\x12\x1b\n\x17INTEGRITY_MODE_STANDARD\x10\x01\x12\x19\n\x15INTEGRITY_MODE_BYPASS\x10\x02*\xbe\x01\n\x08Platform\x12\x18\n\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x18\n\x14PLATFORM_WINDOWS_X64\x10\x01\x12\x1a\n\x16PLATFORM_WINDOWS_ARM64\x10\x02\x12\x16\n\x12PLATFORM_LINUX_X64\x10\x03\x12\x18\n\x14PLATFORM_LINUX_ARM64\x10\x04\x12\x16\n\x12PLATFORM_MACOS_X64\x10\x05\x12\x18\n\x14PLATFORM_MACOS_ARM64\x10\x06\x42\x1f\n\x1bnet.mcsgroup.launcher.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033net.mcsgroup.launcher.protoP\001'
  _globals['_INTEGRITYMODE']._serialized_start=93
  _globals['_INTEGRITYMODE']._serialized_end=196
  _globals['_PLATFORM']._serialized_start=199
  _globals['_PLATFORM']._serialized_end=389
  _globals['_PLAYERPROFILE']._serialized_start=26
  _globals['_PLAYERPROFILE']._serialized_end=91
# @@protoc_insertion_point(module_scope)
