# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mcproto.protos.update_pb2 as update__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in update_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UpdateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFileTree = channel.unary_unary(
                '/launcher.UpdateService/GetFileTree',
                request_serializer=update__pb2.FileTreeRequest.SerializeToString,
                response_deserializer=update__pb2.FileTreeResponse.FromString,
                _registered_method=True)
        self.DownloadFiles = channel.unary_stream(
                '/launcher.UpdateService/DownloadFiles',
                request_serializer=update__pb2.DownloadRequest.SerializeToString,
                response_deserializer=update__pb2.FileChunk.FromString,
                _registered_method=True)
        self.GetAssetFileTree = channel.unary_unary(
                '/launcher.UpdateService/GetAssetFileTree',
                request_serializer=update__pb2.AssetFileTreeRequest.SerializeToString,
                response_deserializer=update__pb2.FileTreeResponse.FromString,
                _registered_method=True)
        self.DownloadAssetFiles = channel.unary_stream(
                '/launcher.UpdateService/DownloadAssetFiles',
                request_serializer=update__pb2.AssetDownloadRequest.SerializeToString,
                response_deserializer=update__pb2.FileChunk.FromString,
                _registered_method=True)
        self.GetJavaFileTree = channel.unary_unary(
                '/launcher.UpdateService/GetJavaFileTree',
                request_serializer=update__pb2.JavaFileTreeRequest.SerializeToString,
                response_deserializer=update__pb2.FileTreeResponse.FromString,
                _registered_method=True)
        self.DownloadJavaFiles = channel.unary_stream(
                '/launcher.UpdateService/DownloadJavaFiles',
                request_serializer=update__pb2.JavaDownloadRequest.SerializeToString,
                response_deserializer=update__pb2.FileChunk.FromString,
                _registered_method=True)
        self.GetFallbackNode = channel.unary_unary(
                '/launcher.UpdateService/GetFallbackNode',
                request_serializer=update__pb2.GetFallbackNodeRequest.SerializeToString,
                response_deserializer=update__pb2.GetFallbackNodeResponse.FromString,
                _registered_method=True)


class UpdateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFileTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetFileTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadAssetFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJavaFileTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadJavaFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFallbackNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFileTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileTree,
                    request_deserializer=update__pb2.FileTreeRequest.FromString,
                    response_serializer=update__pb2.FileTreeResponse.SerializeToString,
            ),
            'DownloadFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFiles,
                    request_deserializer=update__pb2.DownloadRequest.FromString,
                    response_serializer=update__pb2.FileChunk.SerializeToString,
            ),
            'GetAssetFileTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetFileTree,
                    request_deserializer=update__pb2.AssetFileTreeRequest.FromString,
                    response_serializer=update__pb2.FileTreeResponse.SerializeToString,
            ),
            'DownloadAssetFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadAssetFiles,
                    request_deserializer=update__pb2.AssetDownloadRequest.FromString,
                    response_serializer=update__pb2.FileChunk.SerializeToString,
            ),
            'GetJavaFileTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJavaFileTree,
                    request_deserializer=update__pb2.JavaFileTreeRequest.FromString,
                    response_serializer=update__pb2.FileTreeResponse.SerializeToString,
            ),
            'DownloadJavaFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadJavaFiles,
                    request_deserializer=update__pb2.JavaDownloadRequest.FromString,
                    response_serializer=update__pb2.FileChunk.SerializeToString,
            ),
            'GetFallbackNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFallbackNode,
                    request_deserializer=update__pb2.GetFallbackNodeRequest.FromString,
                    response_serializer=update__pb2.GetFallbackNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'launcher.UpdateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('launcher.UpdateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UpdateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFileTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/launcher.UpdateService/GetFileTree',
            update__pb2.FileTreeRequest.SerializeToString,
            update__pb2.FileTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/launcher.UpdateService/DownloadFiles',
            update__pb2.DownloadRequest.SerializeToString,
            update__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssetFileTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/launcher.UpdateService/GetAssetFileTree',
            update__pb2.AssetFileTreeRequest.SerializeToString,
            update__pb2.FileTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadAssetFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/launcher.UpdateService/DownloadAssetFiles',
            update__pb2.AssetDownloadRequest.SerializeToString,
            update__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJavaFileTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/launcher.UpdateService/GetJavaFileTree',
            update__pb2.JavaFileTreeRequest.SerializeToString,
            update__pb2.FileTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadJavaFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/launcher.UpdateService/DownloadJavaFiles',
            update__pb2.JavaDownloadRequest.SerializeToString,
            update__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFallbackNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/launcher.UpdateService/GetFallbackNode',
            update__pb2.GetFallbackNodeRequest.SerializeToString,
            update__pb2.GetFallbackNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
